AWSTemplateFormatVersion: "2010-09-09"
Description: "This template provisions North-South traffic routing. Also provisions Bastion to Member Workload routing."
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Member Account Details
        Parameters:
          - AccountId
          - Region
          - MemberVpcId
          - MemberCidr
      - Label:
          default: Network Hub Details
        Parameters:
          - HubInternalVpcId
          - HubInternalSubnetId
          - HubEgressVpcId
          - TransitGatewayId
      - Label:
          default: Lambda Automation
        Parameters:
          - S3BucketParam
          - S3KeyParam
Parameters:
  AccountId:
    Type: String
    Description: Requestor Account Id
    Default: 172489758104
  Region:
    Type: String
    Description: Requestor Account Region
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - eu-north-1
      - ca-central-1
      - ap-south-1
      - ap-southeast-2
      - eu-west-1
      - eu-west-3
      - us-east-2
      - us-west-2
      - ap-northeast-2
      - ap-southeast-1
      - eu-central-1
      - ap-northeast-1
      - sa-east-1
      - eu-west-2
  MemberVpcId:
    Type: String
    Description: Member Account VPC Id
  MemberCidr:
    Type: String
    Description: Member Account Cidr
  HubInternalVpcId:
    Type: AWS::EC2::VPC::Id
    Description: Network Hub Internal VPC
  HubInternalSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Network Hub Internal VPC Subnet
  HubEgressVpcId:
    Type: AWS::EC2::VPC::Id
    Description: Network Hub Egress VPC
  TransitGatewayId:
    Type: String
    Description: Select Transit Gateway
  S3BucketParam:
    Type: String
    Description: S3 Bucket for Lambda automation
    Default: 'sh-network-dev-bucket1'
  S3KeyParam:
    Type: String
    Description: S3 Key for Lambda automation
    Default: 'northsouth_provider.zip'
Resources:
  NorthSouthProviderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      RoleName: !Sub '${AWS::StackName}-NorthSouthProviderRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-CW-Min'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
      Tags:
        - Key: Owner
          Value: 'rajasekhar.durvasula'
  NorthSouthProviderLambda:
    Type: AWS::Lambda::Function
    UpdateReplacePolicy: Delete
    DependsOn:
      - NorthSouthProviderRole
    Properties:
      FunctionName: !Sub '${AccountId}-NorthSouthProvider'
      Handler: 'northsouth_provider.lambda_handler'
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${NorthSouthProviderRole}'
      Code:
        S3Bucket: !Ref S3BucketParam
        S3Key: !Ref S3KeyParam
      Runtime: python3.9
      MemorySize: 256
      Timeout: 900
      Environment:
        Variables:
          log_level: INFO
          EGRESS_TGW_ROUTETABLE: 'Egress-RTB'
      Tags:
        - Key: Owner
          Value: 'rajasekhar.durvasula'

  SetupNorthSouthProvider:
    Type: Custom::SetupNorthSouthProvider
    DependsOn:
      - NorthSouthProviderRole
      - NorthSouthProviderLambda
    Properties:
      ServiceToken: !GetAtt NorthSouthProviderLambda.Arn
      member_account: !Ref AccountId
      member_region: !Ref Region
      member_vpc_id: !Ref MemberVpcId
      member_cidr: !Ref MemberCidr
      hub_intern_vpc_id: !Ref HubInternalVpcId
      hub_intern_subnet_id: !Ref HubInternalSubnetId
      hub_egress_vpc_id: !Ref HubEgressVpcId
      tgw_id: !Ref TransitGatewayId